// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240319082600_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessObject.Model.AccessLogs", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccessId");

                    b.ToTable("AccessLog");
                });

            modelBuilder.Entity("BusinessObject.Model.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Password = "lf123456",
                            RoleId = "1",
                            Status = 1,
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 130, DateTimeKind.Local).AddTicks(7855),
                            UserId = 1,
                            Username = "LF_adminhuy"
                        },
                        new
                        {
                            AccountId = 2,
                            Password = "lf123456",
                            RoleId = "1",
                            Status = 1,
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(5763),
                            UserId = 2,
                            Username = "LF_adminkhanh"
                        },
                        new
                        {
                            AccountId = 3,
                            Password = "lf123456",
                            RoleId = "1",
                            Status = 1,
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(5779),
                            UserId = 3,
                            Username = "LF_admintuyen"
                        },
                        new
                        {
                            AccountId = 4,
                            Password = "lf123456",
                            RoleId = "1",
                            Status = 1,
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(5781),
                            UserId = 4,
                            Username = "LF_admindao"
                        },
                        new
                        {
                            AccountId = 5,
                            Password = "lf123456",
                            RoleId = "1",
                            Status = 1,
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(5783),
                            UserId = 5,
                            Username = "LF_admintai"
                        });
                });

            modelBuilder.Entity("BusinessObject.Model.Comments", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BusinessObject.Model.LanguageLogs", b =>
                {
                    b.Property<int>("LangLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FromOrTo")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LangLogId");

                    b.ToTable("LanguageLog");
                });

            modelBuilder.Entity("BusinessObject.Model.Pages", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            PageId = 1,
                            PageName = "Intro Screen"
                        },
                        new
                        {
                            PageId = 2,
                            PageName = "Login SDT"
                        },
                        new
                        {
                            PageId = 3,
                            PageName = "Login Gmail"
                        },
                        new
                        {
                            PageId = 4,
                            PageName = "Home"
                        },
                        new
                        {
                            PageId = 5,
                            PageName = "Translate Text"
                        },
                        new
                        {
                            PageId = 6,
                            PageName = "Translate Speech"
                        },
                        new
                        {
                            PageId = 7,
                            PageName = "Translate Image"
                        },
                        new
                        {
                            PageId = 8,
                            PageName = "News"
                        },
                        new
                        {
                            PageId = 9,
                            PageName = "Weather"
                        },
                        new
                        {
                            PageId = 10,
                            PageName = "Weather Detail"
                        },
                        new
                        {
                            PageId = 11,
                            PageName = "Profile"
                        },
                        new
                        {
                            PageId = 12,
                            PageName = "Welcome"
                        },
                        new
                        {
                            PageId = 13,
                            PageName = "About Us"
                        },
                        new
                        {
                            PageId = 14,
                            PageName = "Chat Bot"
                        },
                        new
                        {
                            PageId = 15,
                            PageName = "Help"
                        },
                        new
                        {
                            PageId = 16,
                            PageName = "QR Scan"
                        },
                        new
                        {
                            PageId = 17,
                            PageName = "User Guide"
                        },
                        new
                        {
                            PageId = 18,
                            PageName = "Favourite"
                        });
                });

            modelBuilder.Entity("BusinessObject.Model.Rates", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RateNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RateId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("BusinessObject.Model.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BusinessObject.Model.Settings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConversationLanguageFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationLanguageTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureLangTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslationLanguageFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslationLanguageTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UiLanguagePreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SettingId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("BusinessObject.Model.TranslationHistorys", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("SourceLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TranslationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TranslationId");

                    b.ToTable("TranslationHistory");
                });

            modelBuilder.Entity("BusinessObject.Model.Users", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("National")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfBirth = new DateTime(2004, 3, 29, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(7840),
                            Email = "admin1@example.com",
                            FullName = "Admin 1",
                            Gender = "Male",
                            ImageUser = "1.png",
                            National = "VietNam",
                            Phone = "12345671",
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(8550)
                        },
                        new
                        {
                            UserId = 2,
                            DateOfBirth = new DateTime(2004, 4, 8, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9208),
                            Email = "admin2@example.com",
                            FullName = "Admin 2",
                            Gender = "Female",
                            ImageUser = "2.png",
                            National = "VietNam",
                            Phone = "12345672",
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9224)
                        },
                        new
                        {
                            UserId = 3,
                            DateOfBirth = new DateTime(2004, 4, 18, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9226),
                            Email = "admin3@example.com",
                            FullName = "Admin 3",
                            Gender = "Male",
                            ImageUser = "3.png",
                            National = "VietNam",
                            Phone = "12345673",
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9228)
                        },
                        new
                        {
                            UserId = 4,
                            DateOfBirth = new DateTime(2004, 4, 28, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9230),
                            Email = "admin4@example.com",
                            FullName = "Admin 4",
                            Gender = "Female",
                            ImageUser = "4.png",
                            National = "VietNam",
                            Phone = "12345674",
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9232)
                        },
                        new
                        {
                            UserId = 5,
                            DateOfBirth = new DateTime(2004, 5, 8, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9233),
                            Email = "admin5@example.com",
                            FullName = "Admin 5",
                            Gender = "Male",
                            ImageUser = "5.png",
                            National = "VietNam",
                            Phone = "12345675",
                            Timestamp = new DateTime(2024, 3, 19, 15, 26, 0, 131, DateTimeKind.Local).AddTicks(9235)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
